# Generated by Django 4.1.7 on 2023-03-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
