# Generated by Django 4.1.7 on 2023-03-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_author_options_author_bio_author_email_and_more'),
        ('course', '0003_delete_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.author'),
        ),
    ]
