# Generated by Django 4.1.7 on 2023-03-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_section_options_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturecomment',
            old_name='reply_lecture_comment_id',
            new_name='parent_comment',
        ),
    ]
