# Generated by Django 4.1.7 on 2023-03-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_course_id_certificate_course_and_more'),
        ('course', '0006_rename_reply_lecture_comment_id_lecturecomment_parent_comment'),
    ]

    operations = [
    ]
