# Generated by Django 4.1.7 on 2023-03-14 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_alter_certificate_course_alter_certificate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
