# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_certificate_course_alter_certificate_user_and_more'),
        ('course', '0009_course_text_for_certificate_alter_certificate_course_and_more'),
    ]

    operations = [
    ]
