# Generated by Django 4.1.7 on 2023-03-11 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='schedule time'),
        ),
        migrations.AlterField(
            model_name='notificationview',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_views', to='about.notification'),
        ),
    ]
