# Generated by Django 4.1.7 on 2023-03-10 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationview',
            name='about',
        ),
        migrations.AddField(
            model_name='notificationview',
            name='notification',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='about.notification'),
            preserve_default=False,
        ),
    ]
