# Generated by Django 4.1.7 on 2023-03-11 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0002_rename_phone_advertisement_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationview',
            name='device_id',
        ),
        migrations.AlterField(
            model_name='notificationview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
