# Generated by Django 4.1.7 on 2023-03-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_notificationview_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
