# Generated by Django 4.1.7 on 2023-03-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useterm',
            options={},
        ),
    ]
