# Generated by Django 4.1.7 on 2023-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postview_post_alter_postview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
