# Generated by Django 4.1.7 on 2023-03-10 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('female', 'female')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='photos/avatar%Y%m%d/'),
        ),
    ]
