# Generated by Django 4.1.7 on 2023-03-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_author_options_author_bio_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='photos/avatar/%Y/%m/%d/'),
        ),
    ]
