# Generated by Django 4.1.7 on 2023-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercodeconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('PHONE_ENTERED', 'PHONE_ENTERED'), ('CODE_VERIFIED', 'CODE_VERIFIED'), ('DONE', 'DONE')], default='NEW', max_length=20),
        ),
    ]
