# Generated by Django 4.1.7 on 2023-03-14 19:22

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos/avatars/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
