# Generated by Django 4.1.7 on 2023-03-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_rename_course_id_certificate_course_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_user_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='course.course', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('uzcard', 'payme'), ('apelsin', 'apelsin'), ('visa', 'visa'), ('click', 'click'), ('mastercard', 'mastercard'), ('kpay', 'kpay'), ('cash', 'cash')], max_length=20, null=True, verbose_name='Payment_type'),
        ),
        migrations.AddField(
            model_name='payment',
            name='prayer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='Payer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('not puchased', 'not puchased'), ('in progres', 'in progres'), ('purchased', 'purchased')], default='not puchased', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
