# Generated by Django 4.1.7 on 2023-03-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='prayer',
            new_name='payer',
        ),
    ]
