# Generated by Django 4.1.7 on 2023-03-15 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_rename_prayer_payment_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to=settings.AUTH_USER_MODEL, verbose_name='Payer'),
        ),
    ]
